# Version History
# https://grafana.com/grafana/download
# https://dl.grafana.com/oss/release/grafana_6.1.4_amd64.deb
# https://dl.grafana.com/oss/release/grafana-6.1.4-1.x86_64.rpm


grafana_version: 6.1.4
grafana_pkg_name: grafana_{{grafana_version}}_amd64.deb
grafana_pkg_url: https://dl.grafana.com/oss/release/{{grafana_pkg_name}}
